# Generated by Django 3.1.2 on 2020-11-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20201120_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='name',
        ),
    ]
