# Generated by Django 3.1.2 on 2020-11-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_remove_imageupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='img',
            field=models.ImageField(upload_to='face_images', verbose_name='Image'),
        ),
    ]
